<ul class="resources">
<?php
$content = '';
foreach ($this->entrypoints as $k => $v) {
    $nodeId = lcfirst(str_replace(' ', '', ucwords(str_ireplace(array('\\', '\\\\', '/'), ' ', $k))));

    $content = '';
    $content .= $this->partial('enrise/workbench/index/resource', array('data' => $v));
    $id = 'resource_' . $nodeId;

                if (0 < strlen($content)) {
                    ?>
                    <li class="resource" id="<?php echo $id ?>">
                        <div class="heading">
                            <h2>
                                <a href="#!/<?php echo $nodeId ?>">/<?php echo $k ?></a>
                            </h2>
                        </div>
                        <ul class="endpoints">
                            <?php echo $content; ?>
                        </ul>
                    </li>
                <?php
                }
            }

?>
</ul>
