<?php
use Zend\Form\Element;
var_dump($this->data['route']);


if (isset($this->data['config']['resource_http_methods'])) {
    ?>
    <li class="endpoint">
    <ul class="operations">
    <?php
    foreach ($this->data['config']['resource_http_methods'] as $method) {

        $url = $this->data['route']['options']['route'];
        $nodeId = $method.'_'.$url;
        $listClass = array($method, 'operation');
        $jslink = '#!/' . $nodeId;
        ?>
                <li id="list_<?php echo $nodeId ?>" class="<?php echo implode(' ', $listClass) ?>">
                    <div class="heading">
                        <h3>
                            <span class="http_method">
                                <a onclick="Docs.toggleOperationContent('<?php echo $nodeId ?>');" href="<?php echo $jslink ?>"><?php echo $method ?></a>
                            </span>
                            <span class="path">
                                <a onclick="Docs.toggleOperationContent('<?php echo $nodeId ?>');" href="<?php echo $jslink ?>"><?php echo $url ?></a>
                            </span>
                        </h3>
                        <ul class="options">

                        </ul>
                    </div>
                    <div id="<?php echo $nodeId ?>" class="content hidden">
                        <form method="post" class="sandbox" action="<?php echo $this->url('enrise-apigility-workbench/apiproxy') ?>" accept-charset="UTF-8">
                            <div style="margin:0;padding:0;display:inline">
                                <input type="hidden" value="✓" name="misc[utf8]" />
                                <input type="hidden" value="" name="misc[authenticity_token]" />
                            </div>
                            <h4>Description</h4>
                            <p class="description"><?php //echo nl2br($this->escape($this->endpoint->getDescription())) ?></p>
                            <h4>Parameters</h4>
                            <table class="fullwidth">
                                <thead>
                                <tr>
                                    <th>Parameter</th>
                                    <th><?php //echo ($this->endpoint->isDisabledCommit() ? 'Default' : '' )?> Value</th>
                                    <th>Description</th>
                                </tr>
                                </thead>
                                <tbody>
                                <?php
                                $fields = (array)$this->data['config']['identifier_name'];
                                $group  = array();
                                foreach ($fields as $fieldName => $field) {
                                    $tdCssClasses = array('code');

                                    ?>
                                    <tr>
                                        <td width="100"><?php echo $field ?></td>
                                        <td width="100" class="<?php echo implode(' ', $tdCssClasses) ?>">
                                            <?php
                                            $elm = new Element\Text($field);
                                            echo $this->formText($elm);
                                            ?>
                                        </td>
                                        <td width="500">
                                            <strong><?php //echo $field->getDescription() ?></strong>
                                        </td>
                                    </tr>
                                <?php
                                }
                                $fields = $this->data['config']['collection_query_whitelist'];
                                foreach ($fields as $fieldName => $field) {
                                    $tdCssClasses = array('code');
                                    ?>
                                    <tr>
                                        <td width="100">
                                            <?php
                                            echo $fieldName;
                                            ?></td>
                                        <td width="100" class="<?php echo implode(' ', $tdCssClasses) ?>">
                                            <?php echo $field ?>
                                        </td>
                                        <td width="500">
                                            <strong><?php echo $field ?></strong>
                                        </td>
                                    </tr>
                                <?php
                                }
                                ?>
                                </tbody>
                            </table>

                            <input type="hidden" value="<?php echo $method ?>" name="core[http_method]" />
                            <input type="hidden" value="<?php echo $url ?>" name="core[path]" />
                            <input type="hidden" value="<?php echo $nodeId ?>_sandbox_response" name="misc[dom_id]" />
                            <div id="<?php echo $nodeId ?>_sandbox_response_header" class="sandbox_header">
                                <input type="submit" value="Try it out!" name="commit" id="<?php echo $nodeId ?>_sandbox_response_button" class="submit" />
                                <!-- <button class="submit" type="submit"><span class="icon"></span></button> -->
                                <a style="display: none;" onclick="$('#<?php echo $nodeId ?>_sandbox_response').slideUp();$(this).fadeOut();return false;" id="<?php echo $nodeId ?>_sandbox_response_hider" href="#">Hide Response</a>
                                <div class="throbber" style="display:none"></div>
                            </div>
                        </form>

                        <div style="display:none" id="<?php echo $nodeId ?>_sandbox_response" class="response">
                            <?php
                            /*$mapping = array(
                                'response_code' => 'Response Code',
                                'response_body' => 'Response Body / <a href="" class="expandBody">Open</a>',
                                'response_headers' => 'Response Headers',
                                'request_url' => 'Request URL',
                                'request_last' => 'Last Request',
                                'response_time' => 'Response Time',
                            );
                            $order = $this->registry()->query('settings.workbench.view.responseData', array_flip(array_keys($mapping)));
                            if (is_string($order)) {
                                $order = array_flip(array_map('trim', explode(',', $order)));
                            }
                            $order = array_intersect_key($mapping, (array) $order);
                            foreach ($order as $k => $v) {
                                printf('<h4>%s</h4><div class="%s"></div>', $v, $k);
                            }*/
                            ?>

                        </div>
                    </div>
                </li>
        <?php
    }
    ?>
    </ul>
    </li>
    <?php
}
