<?php
use Zend\Form\Element;

if (isset($this->data['config']['resource_http_methods'])) {
    ?>
    <li class="endpoint">
    <ul class="operations">
    <?php
    foreach ($this->data['config']['resource_http_methods'] as $method) {

        $url = $this->data['route']['options']['route'];
        $nodeId = $method.'_'.$url;
        $listClass = array(strtolower($method), 'operation');
        $jslink = '#!/' . $nodeId;
        $version = $this->data['route']['options']['defaults']['version'];
        ?>
                <li id="list_<?php echo $nodeId ?>" class="<?php echo implode(' ', $listClass) ?>">
                    <div class="heading">
                        <h3>
                            <span class="http_method">
                                <a onclick="Docs.toggleOperationContent('<?php echo $nodeId ?>');" href="<?php echo $jslink ?>"><?php echo $method ?></a>
                            </span>
                            <span class="path">
                                <a data-endpoint-div='<?php echo md5($nodeId) ?>' href="<?php echo $jslink ?>" class="toggler"><?php echo $url ?></a>
                            </span>
                        </h3>
                        <ul class="options">

                        </ul>
                    </div>
                    <div id="<?php echo md5($nodeId); ?>" class="content hidden">
                        <form method="post" class="sandbox" action="<?php echo $this->url('enrise-apigility-workbench/apiproxy') ?>" accept-charset="UTF-8">
                            <h4>Parameters</h4>
                            <table class="fullwidth">
                                <thead>
                                <tr>
                                    <th>Parameter</th>
                                    <th>Value</th>
                                    <th>Description</th>
                                </tr>
                                </thead>
                                <tbody>
                                <tr>
                                    <td width="100">Accept</td>
                                    <td width="100" class="<?php echo implode(' ', array('code')) ?>">
                                        <?php
                                        $accept = array_combine(array_values($this->data['accept']), array_values($this->data['accept']));

                                        $elm = new Element\Select('core[accept]');
                                        $elm->setValueOptions($accept);
                                        echo $this->formSelect($elm);
                                        ?>
                                    </td>
                                    <td width="500">
                                        <strong>HTTP Header</strong>
                                    </td>
                                </tr>
                                <?php
                                if (in_array($method, array('POST', 'PUT', 'PATCH'))) {
                                ?>
                                <tr>
                                    <td width="100">Content-Type</td>
                                    <td width="100" class="<?php echo implode(' ', array('code')) ?>">
                                        <?php
                                        $contentType = array_combine(array_values($this->data['content_type']), array_values($this->data['content_type']));

                                        $elm = new Element\Select('core[content_type]');
                                        $elm->setValueOptions($contentType);
                                        echo $this->formSelect($elm);
                                        ?>
                                    </td>
                                    <td width="500">
                                        <strong>HTTP header</strong>
                                    </td>
                                </tr>
                                <?php
                                }
                                $fields = (array)$this->data['config']['identifier_name'];
                                $group  = array();
                                foreach ($fields as $fieldName => $field) {
                                    $tdCssClasses = array('code');

                                    ?>
                                    <tr>
                                        <td width="100"><?php echo $field ?></td>
                                        <td width="100" class="<?php echo implode(' ', $tdCssClasses) ?>">
                                            <?php
                                            $elm = new Element\Text('params['.$field.']');
                                            echo $this->formText($elm);
                                            ?>
                                        </td>
                                        <td width="500">
                                            <strong>REST param</strong>
                                        </td>
                                    </tr>
                                <?php
                                }
                                $fields = $this->data['config']['collection_query_whitelist'];
                                foreach ($fields as $fieldName => $field) {
                                    $tdCssClasses = array('code');
                                    ?>
                                    <tr>
                                        <td width="100">
                                            <?php
                                            echo $fieldName;
                                            ?></td>
                                        <td width="100" class="<?php echo implode(' ', $tdCssClasses) ?>">
                                            <?php echo $field ?>
                                        </td>
                                        <td width="500">
                                            <strong>Query param</strong>
                                        </td>
                                    </tr>
                                <?php
                                }
                                if (in_array($method, array('POST', 'PUT', 'PATCH'))) {
                                    ?>
                                    <tr>
                                        <td width="100">Body</td>
                                        <td colspan="2" width="600" class="<?php echo implode(' ', array('code')) ?>">
                                            <?php
                                            $elm = new Element\Textarea('rawparams[body]');
                                            $elm->setAttribute('cols', 100);
                                            echo $this->formTextarea($elm);
                                            ?>
                                        </td>
                                    </tr>
                                    <?php
                                }
                                ?>
                                </tbody>
                            </table>

                            <input type="hidden" value="<?php echo $method ?>" name="core[http_method]" />
                            <input type="hidden" value="<?php echo $url ?>" name="core[path]" />
                            <input type="hidden" value="http://<?php echo $_SERVER['HTTP_HOST']; ?>" name="core[host]" />
                            <input type="hidden" value="<?php echo $nodeId ?>_sandbox_response" name="misc[dom_id]" />
                            <input type="hidden" value="<?php echo $version; ?>" name="params[version]" />
                            <div id="<?php echo $nodeId ?>_sandbox_response_header" class="sandbox_header">
                                <input type="submit" value="Try it out!" name="commit" id="<?php echo $nodeId ?>_sandbox_response_button" class="submit" />
                                <!-- <button class="submit" type="submit"><span class="icon"></span></button> -->
                                <a style="display: none;" onclick="$('#<?php echo $nodeId ?>_sandbox_response').slideUp();$(this).fadeOut();return false;" id="<?php echo $nodeId ?>_sandbox_response_hider" href="#">Hide Response</a>
                                <div class="throbber" style="display:none"></div>
                            </div>
                        </form>

                        <div style="display:none" id="<?php echo $nodeId ?>_sandbox_response" class="response">
                            <?php
                            /*$mapping = array(
                                'response_code' => 'Response Code',
                                'response_body' => 'Response Body / <a href="" class="expandBody">Open</a>',
                                'response_headers' => 'Response Headers',
                                'request_url' => 'Request URL',
                                'request_last' => 'Last Request',
                                'response_time' => 'Response Time',
                            );
                            $order = $this->registry()->query('settings.workbench.view.responseData', array_flip(array_keys($mapping)));
                            if (is_string($order)) {
                                $order = array_flip(array_map('trim', explode(',', $order)));
                            }
                            $order = array_intersect_key($mapping, (array) $order);
                            foreach ($order as $k => $v) {
                                printf('<h4>%s</h4><div class="%s"></div>', $v, $k);
                            }*/
                            ?>

                        </div>
                    </div>
                </li>
        <?php
    }
    ?>
    </ul>
    </li>
    <?php
}
