<?php echo $this->doctype(); ?>

<html lang="en" ng-app="zf-api-first-admin">
<head>
    <meta charset="utf-8">
    <?php
    echo $this->headTitle('Apigility workbench');
    echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0');
    echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->appendStylesheet('/css/main.css');
    echo $this->headScript()
        ->prependFile('/js/bootstrap.min.js')
        ->prependFile('/js/jquery.min.js');
    ?>
    <style>
        body {
            padding-top: 80px;
        }
    </style>

</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top za1-nav">
    <div class="container">
        <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath() . '/img/zfapi_logo.png' ?>"></a>
        <ul class="nav navbar-nav">
            <?php if (class_exists('ZF\ApiFirstAdmin\Module', false)): ?>
                <li class="active"><a href="/admin">Setup</a></li>
            <?php endif; ?>
        </ul>
    </div>
</div>



<div class="container">
    <?php echo $this->content; ?>
    <hr>
    <footer>
        <p>&copy; <?php echo date('Y') ?> by Enrise B.V.</p>
    </footer>
</div> <!-- /container -->
<?php echo $this->inlineScript() ?>
<script type="text/javascript" src="<?php echo $this->basePath('/apigility-workbench/js/workbench.js'); ?>"></script>
</body>
</html>
