<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<!-- +++++++++++++++++++++++++++++++++++++++++++++++++ -->
<!--                                                   -->
<!--  Powered by Enrise.com | creative web technology  -->
<!--      handicraft coding & scripting since 1883     -->
<!--            Amersfoort - The Netherlands           -->
<!--                 david@enrise.com                  -->
<!--                                                   -->
<!-- +++++++++++++++++++++++++++++++++++++++++++++++++ -->
<head>
    <meta charset="utf-8">
    <?php
    echo $this->headTitle('Apigility workbench');
    echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0');
    echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/apigility-workbench/img/favicon.ico'))
        ->appendStylesheet($this->basePath('/apigility-workbench/css/main.css'));
    echo $this->headScript()
        ->prependFile('/js/bootstrap.min.js')
        ->prependFile('/js/jquery.min.js');
    ?>
</head>
<body>
<div id="wrapper">
    <div id="header">
        <h1>Apigility API Workbench</h1>
        <noscript><p>This application works best and only for now with Javascript enabled</p></noscript>
    </div>

    <div id="content">
        <div class="container">
            <div class="fullwidth_column">
                <?php echo $this->content; ?>
            </div>
        </div>
    </div>

</div>


    <footer>
        <p>&copy; <?php echo date('Y') ?> by Enrise B.V.</p>
    </footer>
<?php echo $this->inlineScript() ?>
<script type="text/javascript" src="<?php echo $this->basePath('/apigility-workbench/js/workbench.js'); ?>"></script>
</body>
</html>
